### ISSUE TITLE
Why is everything in a single header file?

### ISSUE THREAD

**Issue by vitkarpov** [charypar/immutable#2]
Just a question :)

**Comment by charypar** [comment]
It's actually just one thing - an immutable Map. It was always supposed to be at most two types. Splitting them across two headers felt unnecessary. I think. It's been _a while_ :)

This was my way of diving into C++ 11 with an interesting problem. I never got around to finishing the Vector (or other features of the Map either).

**Comment by vitkarpov** [comment]
Okay, got it :) Watched you video from ReactLondon about Graphql, awesome talk, man. Thank you.
